Update registration-processor-default.properties
mosip/mosip-config pull request #2687
Opened 2022-09-19 14:40 UTC by Sanjayss04

2022-09-19 16:13 UTC, vishwa-vyom requested changes

2022-09-19 16:13 UTC, vishwa-vyom commented on registration-processor-default.properties
> +registration.processor.reprocess.minutes=0,15,30,45,60,75,90,105,120,135,150
this is cron timing, so values should be between 0 to 59

2022-09-20 05:07 UTC, Sanjayss04 commented
@vishwa-vyom Please review.

2022-09-20 05:14 UTC, vishwa-vyom approved these changes

2022-09-21 05:04 UTC, merged