Performance Fix Added
mosip/mosip-config pull request #2690
Opened 2022-09-20 06:07 UTC by kavyainfystrat

To improve the performance we are added the philsys 1.1.5.5 config to Mosip config develop1-v3

2022-09-20 11:27 UTC, vishwa-vyom requested changes

2022-09-20 11:27 UTC, vishwa-vyom commented on kernel-default.properties
> +mosip.kernel.notification.email.from=do-not-reply@mosip.io
why this change done ?

2022-09-20 11:29 UTC, kavyainfystrat commented
This is not done from my end

On Tue, Sep 20, 2022, 4:57 PM Vishwa ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In kernel-default.properties
> <https://github.com/mosip/mosip-config/pull/2690#discussion_r975232524>:
>
> > @@ -49,8 +49,7 @@ mosip.kernel.sms.sender=sender
>  mosip.kernel.sms.unicode=unicode
>
>  ## Email notification
> -
> ***@***.***
> ***@***.***
>
> why this change done ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mosip/mosip-config/pull/2690#pullrequestreview-1113635049>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATJSB5FD3IQ6WPHRXWKXUFLV7GNSBANCNFSM6AAAAAAQQXEKWE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-28 07:18 UTC, vishwa-vyom approved these changes

2022-11-28 07:18 UTC, merged