Mosip 27209 develop v3
mosip/mosip-config pull request #4016
Opened 2023-06-20 09:52 UTC by sowmya695

2024-01-23 13:50 UTC, vishwa-vyom requested changes

2024-01-23 13:50 UTC, vishwa-vyom commented on registration-processor-camel-routes-new-default.xml
> +         </when>
Infant to be removed, since it is a part of different Jira id

2024-01-23 13:50 UTC, vishwa-vyom commented on registration-processor-camel-routes-new-default.xml
> +            <to uri="eventbus://verification-bus-in" />
Lets remove this, since it does not make sense to check this after the biodedup

2024-01-23 13:50 UTC, vishwa-vyom commented on registration-processor-camel-routes-new-default.xml
> +            <to uri="eventbus://verification-bus-in" />
this also to be removed

2024-01-23 13:50 UTC, vishwa-vyom commented on registration-processor-camel-routes-opencrvs_new-default.xml
> +            <to uri="eventbus://verification-bus-in" />
Is valid is and order are not considered, lets test all the changes

2024-01-23 13:50 UTC, vishwa-vyom commented on registration-processor-default.properties
> +mosip.regproc.packet.classifier.tagging.reg-client-current-version=1.2.1-SNAPSHOT
Last to be removed, and previous to be renamed as mosip.regproc.packet.classifier.tagging.exceptionbiometrics.before-exception-metainfo-change.reg-client-versions

2024-02-06 09:39 UTC, sowmya695 commented
@vishwa-vyom  I will cancel this  PR and i will raise new PR because this branch is too told against develop and many conflicts while rebasing so.It contains more than 390 commits and conflicts to resolve.

2024-02-06 09:39 UTC, closed without merging