MOSIP-12805 config changes
mosip/mosip-config pull request #420
Opened 2021-04-15 12:50 UTC by sowmya695

2021-04-20 15:55 UTC, vishwa-vyom requested changes

2021-04-20 15:55 UTC, vishwa-vyom commented on sandbox/registration-processor-mz.properties
> +mosip.regproc.camelbridge.pause-settings=[{"matchExpression": "$.tags[?(@['META_INFO-META_DATA-centerId'] == '10002')]","pauseFor": 432000,"defaultResumeAction": "RESUME_PROCESSING","fromAddress": ".
use the match expression with HOTLISTED = operator and other condition as before

2021-04-20 15:55 UTC, vishwa-vyom commented on sandbox/registration-processor-mz.properties
> +mosip.regproc.camelbridge.pause-settings=[{"matchExpression": "$.tags[?(@['META_INFO-META_DATA-centerId'] == '10002')]","pauseFor": 432000,"defaultResumeAction": "RESUME_PROCESSING","fromAddress": ".
Also the resume remove tags is missing

2021-04-23 06:00 UTC, vishwa-vyom approved these changes

2021-04-27 04:54 UTC, sowmya695 commented
This code is not merged because of force push,So reopening the PR

2021-04-27 05:29 UTC, merged