[DSD-3315] updated application-default.properties
mosip/mosip-config pull request #4373
Opened 2023-08-29 10:43 UTC by Rakshithb1

2023-08-29 12:42 UTC, sanchi-singh24 approved these changes
@Rakshithb1 This we can go ahead for collab env for pre-registration module and make only 1 language as mandatory

2023-08-29 13:48 UTC, nayakrounak approved these changes
Approved

2023-08-29 15:16 UTC, syedsalman3753 requested changes

2023-08-29 15:16 UTC, syedsalman3753 commented on application-default.properties
> +mosip.mandatory-languages=
Any reason why mandator-language is getting removed?

2023-08-29 15:36 UTC, sanchi-singh24 commented
@syedsalman3753 The changes in the language selection to be mandatory from 2 we want to bring it down to 1 for collab as this environment is for contributors so want to give them easy access to usage of pre-reg

2023-08-30 09:13 UTC, syedsalman3753 approved these changes

2023-08-30 09:13 UTC, merged