Remove VID from request.idtypes.allowed in id-authentication-default.…
mosip/mosip-config pull request #4867
Opened 2023-11-29 05:27 UTC by nandhu-kumar

…properties

As VID service is not available in camdgc-dev env. Hence removing VID from "request.idtypes.allowed"

2023-11-29 06:56 UTC, vishwa-vyom requested changes

2023-11-29 06:56 UTC, vishwa-vyom commented on id-authentication-default.properties
>  request.idtypes.allowed.internalauth=UIN,VID
We can remove from here also, it will be consistent.

2023-11-29 06:58 UTC, vishwa-vyom commented on id-authentication-default.properties
>  request.idtypes.allowed.internalauth=UIN,VID
Also from this mosip.ida.internal.hotlist.idtypes.allowed

2023-11-29 08:20 UTC, vishwa-vyom approved these changes

2023-11-30 07:23 UTC, closed without merging

2023-11-30 07:43 UTC, nandhu-kumar commented
Closing this PR for not adding DCO check