MOSIP-31499: Changed KAFKA_CONSUMER_MAX_POLL_RECORDS value
mosip/mosip-config pull request #5274
Opened 2024-02-07 07:49 UTC by HimajaDhanyamraju2

2024-02-07 16:25 UTC, vishwa-vyom requested changes

2024-02-07 16:25 UTC, vishwa-vyom commented on websub-service.toml
>  MESSAGE_DELIVERY_TIMEOUT = 60.0
Lets update this timeout also to 30

2024-02-08 06:30 UTC, HimajaDhanyamraju2 commented on websub-service.toml
>  MESSAGE_DELIVERY_TIMEOUT = 60.0
Done.

2024-02-08 08:04 UTC, vishwa-vyom approved these changes

2024-02-08 08:04 UTC, merged