added new context into Insurance template and changed the issuar did …
mosip/mosip-config pull request #5358
Opened 2024-02-14 15:57 UTC by kaifk468

…into the configuration as the onld one is not working anymore

2024-02-14 16:06 UTC, vishwa-vyom requested changes

2024-02-14 16:06 UTC, vishwa-vyom commented on esignet-mock.properties
> +mosip.esignet.vciplugin.sunbird-rc.credential-type.InsuranceCredential.static-value-map.issuerId=did:upai:e92b9a5a-1b39-44cc-8801-85216852e778
why we need this change?

2024-02-15 09:55 UTC, kaifk468 commented on esignet-mock.properties
> +mosip.esignet.vciplugin.sunbird-rc.credential-type.InsuranceCredential.static-value-map.issuerId=did:upai:e92b9a5a-1b39-44cc-8801-85216852e778
we need new did as older one is no longer supported

2024-02-15 10:31 UTC, vishwa-vyom approved these changes

2024-02-15 10:32 UTC, merged