[DSD-5264] updated compliance-toolkit-default.properties and data-sha…
mosip/mosip-config pull request #6115
Opened 2024-05-14 12:43 UTC by Rakshithb1

…re-default.properties

2024-05-14 13:09 UTC, mayuradesh commented on compliance-toolkit-default.properties
> -server.servlet.context-path=/v1/toolkit
why have u removed this?

2024-05-14 13:15 UTC, mayuradesh requested changes
added comment

2024-05-15 05:12 UTC, Rakshithb1 commented on compliance-toolkit-default.properties
> -server.servlet.context-path=/v1/toolkit
added back

2024-05-15 05:35 UTC, mayuradesh approved these changes

2024-05-15 06:38 UTC, merged