[DSD-5479] add properties to mock esignet
mosip/mosip-config pull request #6650
Opened 2024-07-02 13:47 UTC by challabeehyv

2024-07-02 14:16 UTC, vishwa-vyom requested changes

2024-07-02 14:16 UTC, vishwa-vyom commented on esignet-mock.properties
> +mosip.esignet.auth-challenge.PIN.max-length=4
why are these not part of default property file ?

2024-07-02 14:20 UTC, vishwa-vyom approved these changes

2024-07-02 14:20 UTC, merged

2024-07-04 08:32 UTC, challabeehyv commented on esignet-mock.properties
> +mosip.esignet.auth-challenge.PIN.max-length=4
i saw in config map that single profiles are used for esignet services, this  should be refractored when seperating issuance from esignet @vishwa-vyom