[ MOSIP-32756 ] Adding readme Changes.
mosip/mosip-config pull request #7537
Opened 2024-11-08 13:00 UTC by Khuddusshariff0022

2024-11-08 14:00 UTC, ashok-ksharma requested changes

2024-11-08 14:00 UTC, ashok-ksharma commented on README.md
> +2. Clone the Mosip config repo [mosip-config](https://github.com/mosip/mosip-config)
Clone the Mosip config repo for required released version [mosip-config](https://github.com/mosip/mosip-config)

2024-11-09 13:44 UTC, Khuddusshariff0022 commented on README.md
> +2. Clone the Mosip config repo [mosip-config](https://github.com/mosip/mosip-config)
Done

2024-11-11 06:34 UTC, ashok-ksharma approved these changes

2024-11-11 11:09 UTC, ckm007 approved these changes

2024-11-11 11:09 UTC, merged